In [1]:
import numpy as np
import pandas as pd

In [2]:
matches = pd.read_csv("IPL.csv")

C:\Users\lenovo\AppData\Local\Temp\ipykernel_11172\190414544.py:1: DtypeWarning: Columns (28,29,30,31,43,46,47,48,51) have mixed types. Specify dtype option on import or set low_memory=False.
  matches = pd.read_csv("IPL.csv")

In [3]:
matches.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_balls,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,1,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,2,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,3,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,4,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False

In [4]:
matches.shape

(283678, 65)

In [5]:
matches.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 283678 entries, 0 to 283677
Data columns (total 65 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         283678 non-null  int64
 1   match_id           283678 non-null  int64
 2   date               283678 non-null  object
 3   match_type         283678 non-null  object
 4   event_name         283678 non-null  object
 5   innings            283678 non-null  int64
 6   batting_team       283678 non-null  object
 7   bowling_team       283678 non-null  object
 8   over               283678 non-null  int64
 9   ball               283678 non-null  int64
 10  ball_no            283678 non-null  float64
 11  batter             283678 non-null  object
 12  bat_pos            283678 non-null  int64
 13  runs_batter        283678 non-null  int64
 14  balls_faced        283678 non-null  int64
 15  bowler             283678 non-null  object
 16  valid_ball         283678 non-null  int64
 17  runs_extras        283678 non-null  int64
 18  runs_total         283678 non-null  int64
 19  runs_bowler        283678 non-null  int64
 20  runs_not_boundary  283678 non-null  bool
 21  extra_type         15493 non-null   object
 22  non_striker        283678 non-null  object
 23  non_striker_pos    283678 non-null  int64
 24  wicket_kind        14106 non-null   object
 25  player_out         14106 non-null   object
 26  fielders           10245 non-null   object
 27  runs_target        136510 non-null  float64
 28  review_batter      907 non-null     object
 29  team_reviewed      907 non-null     object
 30  review_decision    907 non-null     object
 31  umpire             907 non-null     object
 32  umpires_call       283678 non-null  bool
 33  player_of_match    283678 non-null  object
 34  match_won_by       283678 non-null  object
 35  win_outcome        278954 non-null  object
 36  toss_winner        283678 non-null  object
 37  toss_decision      283678 non-null  object
 38  venue              283678 non-null  object
 39  city               283678 non-null  object
 40  day                283678 non-null  int64
 41  month              283678 non-null  int64
 42  year               283678 non-null  int64
 43  season             283678 non-null  object
 44  gender             283678 non-null  object
 45  team_type          283678 non-null  object
 46  superover_winner   3896 non-null    object
 47  result_type        4724 non-null    object
 48  method             3890 non-null    object
 49  balls_per_over     283678 non-null  int64
 50  overs              283678 non-null  int64
 51  event_match_no     283678 non-null  object
 52  stage              283678 non-null  object
 53  match_number       283678 non-null  object
 54  team_runs          283678 non-null  int64
 55  team_balls         283678 non-null  int64
 56  team_wicket        283678 non-null  int64
 57  new_batter         13593 non-null   object
 58  power_surge_start  0 non-null       float64
 59  batter_runs        283678 non-null  int64
 60  batter_balls       283678 non-null  int64
 61  bowler_wicket      283678 non-null  int64
 62  batting_partners   283678 non-null  object
 63  next_batter        13593 non-null   object
 64  striker_out        283678 non-null  bool
dtypes: bool(3), float64(3), int64(24), object(35)
memory usage: 135.0+ MB

In [6]:
matches['innings'].head(20)

0     1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
Name: innings, dtype: int64

In [7]:
matches['runs_total'].dtype

dtype('int64')

In [8]:
total_score_df =matches.groupby(['match_id', 'innings'])['runs_total'].sum().reset_index()

In [9]:
total_score_df = total_score_df[total_score_df['innings'] == 2]

In [10]:
total_score_df.head()

   match_id  innings  runs_total
1    335982        2          82
3    335983        2         207
5    335984        2         132
7    335985        2         166
9    335986        2         112

In [11]:
match_df = matches.merge(total_score_df[['match_id','runs_total']],left_on='match_id', right_on = 'match_id')

In [12]:
match_df.head()

,Unnamed: 0,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,...,team_wicket,new_batter,power_surge_start,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,runs_total_y
0,141607,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,...,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,82
1,141608,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,...,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,82
2,141609,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,0,NaN,NaN,0,1,0,"('BB McCullum', 'SC Ganguly')",NaN,False,82
3,141610,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,...,0,NaN,NaN,0,2,0,"('BB McCullum', 'SC Ganguly')",NaN,False,82
4,141611,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,...,0,NaN,NaN,0,3,0,"('BB McCullum', 'SC Ganguly')",NaN,False,82

In [13]:
match_df['batting_team'].unique()

array(['Kolkata Knight Riders', 'Royal Challengers Bangalore',
       'Chennai Super Kings', 'Kings XI Punjab', 'Rajasthan Royals',
       'Delhi Daredevils', 'Mumbai Indians', 'Deccan Chargers',
       'Kochi Tuskers Kerala', 'Pune Warriors', 'Sunrisers Hyderabad',
       'Rising Pune Supergiants', 'Gujarat Lions',
       'Rising Pune Supergiant', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans',
       'Royal Challengers Bengaluru'], dtype=object)

In [14]:
import numpy as np

teams = np.array([
    "Chennai Super Kings",
    "Mumbai Indians",
    "Kolkata Knight Riders",
    "Royal Challengers Bengaluru",
    "Sunrisers Hyderabad",
    "Rajasthan Royals",
    "Delhi Capitals",
    "Punjab Kings",
    "Lucknow Super Giants",
    "Gujarat Titans"
])

In [15]:
match_df['batting_team'] = match_df['batting_team'].replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru'
})

match_df['bowling_team'] = match_df['bowling_team'].replace({
    'Delhi Daredevils': 'Delhi Capitals',
    'Kings XI Punjab': 'Punjab Kings',
    'Royal Challengers Bangalore': 'Royal Challengers Bengaluru'
})

In [16]:
valid_matches = match_df[
    match_df['batting_team'].isin(teams) &
    match_df['bowling_team'].isin(teams)
]['match_id']

match_df = match_df[match_df['match_id'].isin(valid_matches)]

In [17]:
match_df.shape

(239331, 66)

In [18]:
match_df['season']

0         2007/08
1         2007/08
2         2007/08
3         2007/08
4         2007/08
           ...
283156       2026
283157       2026
283158       2026
283159       2026
283160       2026
Name: season, Length: 239331, dtype: object

In [19]:

match_df['runs_left'] = match_df['runs_target'] - match_df['team_runs']

match_df['balls_left'] = 120 - ((match_df['over'] - 1) * 6 + match_df['ball'])

match_df['wickets_left'] = 10 - match_df['team_wicket']

match_df['total_runs_x'] = match_df['runs_target'] - 1

balls_played = 120 - match_df['balls_left']
match_df['crr'] = (match_df['team_runs'] * 6) / balls_played.replace(0, 1)

match_df['rrr'] = (match_df['runs_left'] * 6) / match_df['balls_left'].replace(0, 1)

match_df['result'] = (
    match_df['batting_team'] == match_df['match_won_by']
).astype(int)

In [20]:
match_df.shape

(239331, 73)

In [21]:
match_df['innings'].unique

<bound method Series.unique of 0         1
1         1
2         1
3         1
4         1
         ..
283156    2
283157    2
283158    2
283159    2
283160    2
Name: innings, Length: 239331, dtype: int64>

In [22]:
match_df = match_df[match_df['innings']==2]

In [23]:
match_df.shape

(115353, 73)

In [24]:
match_df['team_wicket']

124       0
125       0
126       0
127       0
128       0
         ..
283156    3
283157    3
283158    3
283159    3
283160    3
Name: team_wicket, Length: 115353, dtype: int64

In [25]:
 match_df['result']

124       0
125       0
126       0
127       0
128       0
         ..
283156    1
283157    1
283158    1
283159    1
283160    1
Name: result, Length: 115353, dtype: int64

In [26]:
sample_df = match_df[[
    'batting_team',
    'bowling_team',
    'city',
    'runs_left',
    'balls_left',
    'wickets_left',
    'total_runs_x',
    'crr',
    'rrr',
    'result'
]]

In [27]:
sample_df.sample(sample_df.shape[0])

,batting_team,bowling_team,city,runs_left,balls_left,wickets_left,total_runs_x,crr,rrr,result
92317,Delhi Capitals,Punjab Kings,Dharamsala,172.0,123,10,171.0,-0.000000,8.390244,0
245419,Mumbai Indians,Sunrisers Hyderabad,Hyderabad,201.0,88,8,277.0,14.437500,13.704545,0
274804,Rajasthan Royals,Chennai Super Kings,Delhi,104.0,73,9,187.0,10.723404,8.547945,1
217465,Gujarat Titans,Sunrisers Hyderabad,Mumbai,120.0,75,9,195.0,10.133333,9.600000,1
119699,Punjab Kings,Sunrisers Hyderabad,Hyderabad,141.0,92,9,185.0,9.642857,9.195652,0
...,...,...,...,...,...,...,...,...,...,...
187924,Rajasthan Royals,Chennai Super Kings,Abu Dhabi,98.0,99,7,125.0,8.000000,5.939394,1
205396,Delhi Capitals,Chennai Super Kings,Dubai,113.0,107,9,136.0,11.076923,6.336449,1
270311,Mumbai Indians,Sunrisers Hyderabad,Hyderabad,15.0,40,8,143.0,9.675000,2.250000,1
244950,Royal Challengers Bengaluru,Punjab Kings,Bengaluru,78.0,55,7,176.0,9.138462,8.509091,1
267915,Kolkata Knight Riders,Punjab Kings,Mohali,100.0,115,8,111.0,14.400000,5.217391,0

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X = sample_df.iloc[:, :-1]
Y = sample_df.iloc[:, -1]
X_train, X_test,Y_train, Y_test = train_test_split( X,Y,test_size=0.2, random_state=1)

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

trf = ColumnTransformer(
    transformers=[
        ('trf', OneHotEncoder(sparse_output=False, drop='first'),
         ['batting_team', 'bowling_team', 'city'])
    ],
    remainder='passthrough'
)

In [31]:
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [32]:
pipe = Pipeline(steps=[
    ('step1' , trf),
    ('step2' ,LogisticRegression(solver = 'liblinear'))
     ])

In [33]:
pipe.fit(X_train,Y_train)

Pipeline(steps=[('step1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('trf',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['batting_team',
                                                   'bowling_team', 'city'])])),
                ('step2', LogisticRegression(solver='liblinear'))])

In [34]:
X_train.describe()

,runs_left,balls_left,wickets_left,total_runs_x,crr,rrr
count,92282.000000,92282.000000,92282.000000,92282.000000,92282.000000,92282.000000
mean,95.819412,68.943174,7.504486,171.177131,9.465289,8.727792
std,52.193192,33.386181,2.175303,32.789911,8.877016,4.430717
min,-9.000000,6.000000,0.000000,42.000000,-132.000000,-5.000000
25%,55.000000,41.000000,6.000000,150.000000,7.457944,6.556701
50%,95.000000,70.000000,8.000000,171.000000,8.934058,8.304000
75%,135.000000,98.000000,9.000000,192.000000,10.736842,10.168421
max,287.000000,125.000000,10.000000,287.000000,168.000000,102.000000

In [35]:
Y_pred = pipe.predict(X_test)

In [36]:
from sklearn.metrics import accuracy_score

In [37]:
accuracy_score(Y_test,Y_pred)

0.8140956178752546

In [38]:
teams

array(['Chennai Super Kings', 'Mumbai Indians', 'Kolkata Knight Riders',
       'Royal Challengers Bengaluru', 'Sunrisers Hyderabad',
       'Rajasthan Royals', 'Delhi Capitals', 'Punjab Kings',
       'Lucknow Super Giants', 'Gujarat Titans'], dtype='<U27')

In [41]:
match_df['city'].unique()

array(['Bangalore', 'Chandigarh', 'Delhi', 'Mumbai', 'Jaipur', 'Chennai',
       'Kolkata', 'Cape Town', 'Port Elizabeth', 'Durban', 'Centurion',
       'East London', 'Johannesburg', 'Kimberley', 'Bloemfontein',
       'Ahmedabad', 'Dharamsala', 'Pune', 'Hyderabad', 'Raipur', 'Ranchi',
       'Abu Dhabi', 'Unknown', 'Cuttack', 'Visakhapatnam', 'Bengaluru',
       'Indore', 'Dubai', 'Sharjah', 'Navi Mumbai', 'Lucknow', 'Guwahati',
       'Mohali', 'New Chandigarh'], dtype=object)

In [43]:
import pickle
pickle.dump( pipe, open('pipe.pkl','wb'))